### ISSUE TITLE
Issue with Struct fields having a reserved name

### ISSUE THREAD

**Issue by nallagangus** [rcongiu/Hive-JSON-Serde#110]
Is there a known limitation with SerDe when one of the fields happens to be a Hive Reserve Word and it has be referenced with in SERDEPROPERTIEs.

So Json goes like : {"user":{"field1":"v1", "field2:"v2"}, "citycode":23412}
Create table 
userAA struct { field1:string, field2:string)
ROWFormat Serde 'serde'
WITH SERDEPROPERTIES
 { "userAA"="$.user"}

The table is loaded with data but all values are null including all fields in user struct

Thanks
Sudhir

**Comment by nallagangus** [comment]
I mean to say only fields from "struct" are null.. rest of main fields are valid. 

What is the correct syntax for SERDEPROPERTIES to map values from JSON to Table layout especially for "STRUCT" fields? I have to use SERDEPROPERTIES since one of the fields in JSON (USER) is Hive reserved word and cannot us it in table declaration.

**Comment by rcongiu** [comment]
Please refer to rcongiu/Hive-JSON-Serde
|   |
|   |  |   |   |   |   |   |
| rcongiu/Hive-JSON-SerdeHive-JSON-Serde - Read - Write JSON SerDe for Apache Hive. |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


the correct mapping should beWITH SERDEPROPERTIES
( 'mappings.user-' = 'userAA' ) -------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 


     On Sunday, August 2, 2015 4:50 PM, Sudhir Nallagangu <notifications@github.com> wrote:
   

 I mean to say only fields from "struct" are null.. rest of main fields are valid. What is the correct syntax for SERDEPROPERTIES to map values from JSON to Table layout especially for "STRUCT" fields? I have to use SERDEPROPERTIES since one of the fields in JSON (USER) is Hive reserved word and cannot us it in table declaration. —

**Comment by rcongiu** [comment]
No minus sign, sorry that was a typo:the correct mapping should beWITH SERDEPROPERTIES
( 'mappings.user' = 'userAA' ) -------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 


     On Sunday, August 2, 2015 5:46 PM, Roberto Congiu <rcongiu@yahoo.com> wrote:
   

 Please refer to rcongiu/Hive-JSON-Serde
|   |
|   |  |   |   |   |   |   |
| rcongiu/Hive-JSON-SerdeHive-JSON-Serde - Read - Write JSON SerDe for Apache Hive. |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


the correct mapping should beWITH SERDEPROPERTIES
( 'mappings.user-' = 'userAA' ) -------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 


     On Sunday, August 2, 2015 4:50 PM, Sudhir Nallagangu <notifications@github.com> wrote:
   

 I mean to say only fields from "struct" are null.. rest of main fields are valid. What is the correct syntax for SERDEPROPERTIES to map values from JSON to Table layout especially for "STRUCT" fields? I have to use SERDEPROPERTIES since one of the fields in JSON (USER) is Hive reserved word and cannot us it in table declaration. —

**Comment by nallagangus** [comment]
Thanks Rober.
so if "user" is defined in JSON and useraa is defined as a Hive table field. the expression in properties is (mappings.user'='useraa').

Here is complete statement that is returning "NULL" into struct fields.

create EXTERNAL table extbl (
   messagea string,
   useraa struct <
      geoenabled: boolean,
      userid: int >
 )
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES (
 "useraa.geoenabled"="user.geoenabled",
 "useraa.userid"="user.id",
)

JSON file have {"user":{"geoenabled":true,"id":12345},"messagea":string}


The message is coming alone fine. only "STRUCT" fields are not showing up..

**Comment by nallagangus** [comment]
I specifically need to know how we can refer inner nested fields from JSON file. like "user.id" in above example

**Comment by rcongiu** [comment]
You should be able to do
```{sql}
create EXTERNAL table extbl (
messagea string,
useraa struct <
geoenabled: boolean,
userid: int >
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES (
"mappings.useraa"="user"
)
```

then you should be able to do 
```{sql}
select useraa.userid from extbl
```

**Comment by rcongiu** [comment]
I am guessing it worked...reopen if not.
