### ISSUE TITLE
Top level array

### ISSUE THREAD

**Issue by YevheniiStepaniuk** [rcongiu/Hive-JSON-Serde#215]
This serde doesn't work with top-level arrays:
````json
[ { "a": 32}, {"a": 31"}]
````
I've faced with this issue while using your serde, and no way to convert JSON files to valid, through big size. 

How it can be resolved?

**Comment by rcongiu** [comment]
It works as long as there's one object per line. This is a limitation from hadoop, since otherwise files would not be splittable.
-------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 

    On Monday, April 29, 2019, 8:49:05 AM PDT, Yevhenii Stepaniuk <notifications@github.com> wrote:  
 
 
This serde doesn't work with top-level arrays:
[ { "a": 32}, {"a": 31"}]
I've faced with this issue while using your serde, and no way to convert JSON files to valid, through big size.

Have can it be resolved?

**Comment by YevheniiStepaniuk** [comment]
@rcongiu Thanks for the answer, did not know about Hadoop restriction for JSON.
