### ISSUE TITLE
Case Issue for JSON Fields

### ISSUE THREAD

**Issue by sukrit007** [rcongiu/Hive-JSON-Serde#4]
If my input data contains column names which are in mixed case, the SERDE does not recognize those columns and get NULL values while reading their values.

For e.g. if my input is :
{"verb":"getusersessioninfo","actor":"object":{"bookID":4454},"published":"2012-02-18T09:38:43Z"}

My corresponding table is :
create external table books (
    verb string,
       object struct < bookID:string >,
    published string  
  )
  row format 
    serde 'org.openx.data.jsonserde.JsonSerDe'

If I try too read books.bookID , I get NULL.

However if I change my data to 
{"verb":"getusersessioninfo","actor":"object":{"bookid":4454},"published":"2012-02-18T09:38:43Z"} 
it works fine.

Hive is case in-sensitive, however during de-serialization , the cols should be considered as lower case.

**Comment by udayakumarp** [comment]
Hey rcongiu,
     I was getting into this issue while using the SerDe. The default behavior of treating case insensitive may not be appropriate all the time. The source JSON is mostly not under our control and there are quite possible that there are duplicates with different cases to mean different things.

If there was way to to throw an Exception or Warning message, but not prevent processing the whole data just because of 2 or 3 such bad records.

We need to log these bad records, but not stop processing. The way of throwing Exception kind of is a big decision when we are doing heavy processing and there are sequential dependencies of processing from one batch to another batch. If one batch fails because of this, it kind of stalls the whole pipe.

If there a way we can handle this?

Thanks,
Uday.

**Comment by rcongiu** [comment]
Mmm..it shouldn't be too hard to add a feature that sets a threshold for warnings and errors...however, the threshold would be for mapper/reducer, not global , because there's no way the worker could know how many bad records there were on the other workers. 
Something global could be done maybe with counter and pre/post hive hooks.

**Comment by udayakumarp** [comment]
I tried the Hadoop based bad records skip feature. But that doesn't solve this problem - probably does not fit into the category of errors.

Where do we throw the exception currently? In the RecordReader or in the Mapper itself?

Its good to have the kind of feature you are suggesting - where we can have hive level config parameters to control it. I'm okay with the setting being at the mapper/reducer level. That is a fair thing to do. We will not require global control at this point. But being able to skip the records and probably backup these bad records to a different HDFS directory, that will be the ideal thing to do!

What say, Robert? Is this something we can try to do?

Thanks,
Uday.

**Comment by udayakumarp** [comment]
Will the following work for this SerDe as well?

ROW FORMAT SERDE 'some.serde'  
WITH SERDEPROPERTIES ('error.ignore'='true')  

I see some of the other SerDe use this. Is this is a common parameter? Does this SerDe honor this setting?

~Uday.

**Comment by rcongiu** [comment]
it's not a standard, it may make sense for some serdes and not for others. It currently can ignore some malformed json with
ALTER TABLE json_table SET SERDEPROPERTIES ( "ignore.malformed.json" = "true");



     On Friday, May 1, 2015 12:00 AM, Udayakumar <notifications@github.com> wrote:
   

 Will the following work for this SerDe as well?ROW FORMAT SERDE 'some.serde'

WITH SERDEPROPERTIES ('error.ignore'='true') I see some of the other SerDe use this. Is this is a common parameter? Does this SerDe honor this setting?~Uday.—

**Comment by udayakumarp** [comment]
That "ignore.malformed.json" = "true" setting works for me!! :)

But is there a way to backup these bad records so as to get do further processing or do an count for reporting.

Just like the error.ignore or ignore.malformed.json, is there a way to filter out records which falls into this category to a safe place in HDFS.

Thanks,
Uday.

**Comment by rcongiu** [comment]
At the moment they are not really backed up, but they should come up in the hive task logs.
